Vagrant.configure(2) do |config|
	  config.vm.box = "ubuntu/trusty64"
	  config.vm.provider "virtualbox" do |v|
		v.cpus = 1
	  end
	  config.vm.define "vm0" do |vmN|
		  vmN.vm.provision :shell, path: "vm0.sh"
		  vmN.vm.network "private_network", ip: "192.168.2.100"
	  end
	  config.vm.define "vm1" do |vmN|
			vmN.vm.provision :shell, path: "vm1.sh"
			vmN.vm.network "private_network", ip: "192.168.2.101"
		end
		
	end